# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/asus/msm8916-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter Z00ED Z00RD Z00xD Z010D,$(TARGET_DEVICE)),)

endif
